language: ruby
rvm:
  - 2.3
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: _site
  fqdn: docs.krakenengine.com
  on:
    branch: master

